### ISSUE TITLE
Server returned HTTP response code: 405 for URL: http://127.0.0.1:5001/api/v0/version

### ISSUE THREAD

**Issue by MangKyu** [ipfs-shipyard/java-ipfs-http-client#162] opened 2020-05-04 10:57 UTC
IPFS method does not support GET Method.
When i tried to initialize IPFS Object, it occurs an error like below

`Exception in thread "main" java.lang.RuntimeException: IOException contacting IPFS daemon.
Trailer: null 405 - Method Not Allowed

at io.ipfs.api.IPFS.get(IPFS.java:683)
at io.ipfs.api.IPFS.retrieve(IPFS.java:662)
at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:624)
at io.ipfs.api.IPFS.version(IPFS.java:572)
at io.ipfs.api.IPFS.<init>(IPFS.java:69)
at io.ipfs.api.IPFS.<init>(IPFS.java:45)
at Main.main(Main.java:15)
Caused by: java.io.IOException: Server returned HTTP response code: 405 for URL: http://127.0.0.1:5001/api/v0/version
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
at io.ipfs.api.IPFS.get(IPFS.java:671)
... 6 more`

**Comment by red0bear** [comment] 2020-05-10 03:54
Got exact same problem with last version version ipfs

**Comment by IslandGray** [comment] 2020-05-10 09:56
Yes, i got same problem. Please using POST method instead GET

**Comment by FultonBrowne** [comment] 2020-05-10 20:48
same here and I need to work for a big deadline

**Comment by Gxz-NGU** [comment] 2020-05-12 02:27
same here

**Comment by NDCFL** [comment] 2020-05-26 01:07
确实最新版本的出现了405

**Comment by odisseus** [comment] 2020-06-01 21:58
This seems to be the duplicate of #157. 

To everybody affected by this issue, my advice is to keep using IPFS 0.4.x until this library gets updated.

**Closed** 2020-07-31 19:04 UTC
